name: lingua_forge
description: Dein persönlicher Sprachbegleiter mit Flutter.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  provider: any
  shared_preferences: any
  http: any
  intl: any
  flutter_svg: any
  url_launcher: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true

  assets:
    - assets/linguaforge_logo.png
    - assets/data/vocab.json